exp_name: grevyszebra_consistency
species: Grevys zebra
comment: Experiment comment goes here
algorithm_type: gc
data:
  images_dir: /ekaterina/work/data/zebra/images
  separate_by_fields: 
    - encounter
    - viewpoint
  viewpoint_list:
  - right
  name_keys:
  - name_viewpoint
  id_key: annot_uuid
  n_filter_min: 1
  n_filter_max: 10
  annotation_file: /ekaterina/work/data/zebra/annotations/zebra_duplicates.json
  embedding_file: /ekaterina/work/src/MiewID/wbia_miew_id/output/embeddings/zebra_embeddings_duplicates.pickle
  stats_file: tmp/zebra_baseline_prob_098.json
algorithm:
  target_edges: 0
  initial_topk: 10
lca:
  verifier_name: miewid
  db_path: tmp
  temp_db: false
  clear_db: true
  distance_power: 2
  theta: 0.1 
  iterations:
    min_delta_converge_multiplier: 0.95
    min_delta_stability_ratio: 4
    num_per_augmentation: 2
    tries_before_edge_done: 1
    ga_iterations_before_return: 10
    ga_max_num_waiting: 50
    max_human_decisions: 5000
    should_densify: true
    densify_min_number_human: 10
    densify_min_edges: 10
    densify_frac: 0.5
  drawing:
    draw_iterations: false
    drawing_prefix: drawing_lca
edge_weights:
  prob_human_correct: 0.98
  augmentation_names: miewid simulated_human
  num_pos_needed: 300
  num_neg_needed: 50
  scorer: kde
  classifier_thresholds:
    miewid: 0.85
  verifier_names: miewid simulated_human
logging:
  log_level: INFO
  log_file: tmp/logs/whaleshark_kde.log
gc:
  verifier_name: miewid
  theta: 0.1
  validation_step: 20
